version: '3.4'
services :
  web:
    container_name: makentu-machine
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    expose:
      - 8001
    depends_on:
      - db
    networks:
      - makentu-competition
      - nginx
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=MNTU
    networks:
      - makentu-competition
  networks:
    nginx:
      external: true
    makentu-competition:
  