import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeadBar from '../components/HeadBar'
import Providers from './providers'
import { AccountProvider } from '@/context/Account'
import { useContext } from 'react'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children } : { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AccountProvider>
          <HeadBar />
          {children}
        </AccountProvider>
      </body>
    </html>
  )
}
